baseurl: "/"
relativeurls: true
languageCode: "en-us"
title: "Dong"
theme: "hugo-lithium-theme"
googleAnalytics: "UA-43118729-1"
disqusShortname: "Dong"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

permalinks:
  cn: "/cn/:year/:month/:day/:slug/"
  en: "/en/:year/:month/:day/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Blog"
      url: "/en/"
      weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    - name: "博客"
      url: "/cn/"
      weight: 4
      
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "Vitae"
      url: "/en/vitae/"
      weight: 4
    - name: "MetaWorkflow"
      url: "/metaworkflow/"
      weight: 5
    - name: "中文"
      url: "/cn/"
      weight: 6
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/"
      weight: 3
    - name: "简历"
      url: "/cn/vitae/"
      weight: 4
    - name: "English"
      url: "/en/"
      weight: 5

params:
  description: "Personal website of Miao Yu; 于淼的个人网站"
  disqusURL: ""
  fullURL: ""
  dateFormat: "2006/01/02"
  customCSS: ["css/custom.css"]
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js"]
  githubContentURL: "https://github.com/yufree/yufree.cn/edit/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.9.0"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  social:
    twitter: ""
    weibo: ""
    weibo_url: ""
    github: ""

  logo:
    url: "fish.png"
    width: 50
    height: 50
    alt: "Dong"

  author:
    en: "Dong"
    cn: "Dong"

  lang:
    edit:
      en: "Edit this page"
      cn: "编辑本页"
